language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - cd memopol2; ./INIT
# command to run tests
script: nosetests tests
