language: python
python:
  - "2.7"
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python manage.py init
script:
  - echo "Running scripts..."
  - PYTHONPATH=. nosetests
