language: python
python:
  - "2.7"
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - cd memopol2; ./INIT
script:
  - nosetests tests
  - cat tests/debug
